apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubemesh
spec:
  selector:
    matchLabels:
      name: kubemesh
  template:
    metadata:
      labels:
        name: kubemesh
    spec:
      hostNetwork: true # CRITICAL: This lets you see the node's traffic
      containers:
      - name: kubemesh
        image: kubemesh:v3
        securityContext:
          privileged: true # CRITICAL: Accessing kubemesh interfaces requires root-level permissions